output: "lib/bindings3.dart"
headers:
  entry-points:
    - "library/libdtls.h"
  functions:
    include:
      - generateValueKeyMessage
      - PHash
      - VerifyFinishedData
      - GenerateServerCertificate
      - GenerateCurveKeypair
      - GenerateKeySignature
      - GetCertificateFingerprintFromBytes
      - GeneratePreMasterSecret
      - VerifyCertificate
