name: dart_webrtc_nuts_and_bolts
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-334.2.beta

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.6
  convert: ^3.1.2
  pointycastle: ^3.9.1
  asn1lib: ^1.5.8
  logging: ^1.3.0
  basic_utils: ^5.7.0
  cryptography: ^2.7.0
  flutter_curve25519: ^0.1.2
  pinenacl: ^0.6.0
  blockchain_utils: ^3.5.0
  elliptic: ^0.3.11
  pem: ^2.0.5
  cryptography_flutter: ^2.3.2
  ffi: ^2.1.3
  ffigen: ^16.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
