name: dart_webrtc_nuts_and_bolts
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-334.2.beta

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.6
  convert: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
